name: GitHub Actions Demo - workshop3
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_dispatch:
env:
  testvar: 2
jobs:
  Lint:
    runs-on: ubuntu-latest
    env:
      testvar: 3
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "${{ vars.testvar }}, ${{ env.testvar }}"